### ISSUE TITLE
Feature: Inject Puffader into another process

### ISSUE THREAD

**Issue by xp4xbox** [xp4xbox/Puffader#12]

**Comment by ymengesha** [comment]
HI,
can you please further elaborate on the intended feature?

**Comment by xp4xbox** [comment]
I would like to be able to convert this script into a dll which can be ran from memory.

**Comment by xp4xbox** [comment]
I have found a solution for this, instead of injecting the dll into memory, migrating the compiled .exe into a windows process accomplishes the same task.

**Comment by xp4xbox** [comment]
I created a basic injector 7f64dd6.

Although I cannot get it to work for the compiled keylogger.
