### ISSUE TITLE
userpath issue in windows

### ISSUE THREAD

**Issue by tehseensagar** [xp4xbox/Puffader#29]
I've been trying to set path as

C:\Users\%username%\AppData\Local\Microsoft <== does not work out

Actual-user
-------------
C:\Users\michael\AppData\Local\Microsoft <== hard coded username worked

I don't want that path to be hard coded , all I want is to set the path for any user I.E C:\Users\abc\AppData\Local\Microsoft  or like C:\Users\xyz\AppData\Local\Microsoft and rest of the path remain same only user changes. What ever user is logged in and run binary it gets user path and create files there.

Emailing Issue:
----------------
I've setup enabled less secure App in google , yet unable to receive any of email 

Py2exe Compilation
---------------------
Insufficient sysem resources exist to complete the requestd services

Getting above error when compiling via py2exe

Regards

**Comment by xp4xbox** [comment]
In python to use environment variables you have to do something like username = os.environ["USERNAME"]. 

For the email issue, i have just tested it out, works fine. I would double check your settings, make sure you don't have any conflicting settings.

For the py2exe problems, I have never gotten that error before, I would just try again.

**Comment by xp4xbox** [comment]
Also you can only choose one method for storing/sending logs, default is by email. So if you want to store logs local and send them, there will be a conflict.

**Comment by tehseensagar** [comment]
My email setting
------------------
strEmailAc = "xxxxx@gmail.com"
strEmailPass = "Passwd"


Further settings:
-----------------

`blnFTP = "False"  # if using ftp set this to True and configure the options below
strFtpServer = ""
intFtpPort = 21
strFtpUser = ""
strFtpPass = ""
strFtpRemotePath = "/"

intCharPerSend = 10  # set num of chars before send log/store (1000)

blnUseTime = "False"  # if you prefer to use a timer to send/save logs, set this to True
intTimePerSend = 10  # set how often to send/save logs in seconds (120)

blnStoreLocal = "True"  # True to save logs/screens locally
strLogFile = "C:/Users/michael/AppData/Local/Microsoft/Inteldat.txt"  # set non-protected path to text file eg. c:/temp/test.txt

blnLogClick = "False"  # for logging window clicks
blnBackRemove = "False"  # set this to True if you prefer the program removes the last key if the user types backspace

blnScrShot = "True"  # set to True for capturing screenshots
strScrDir = "C:/Users/michael/AppData/Local/Microsoft"  # set non-protected dir for scrshot location if storing locally. eg c:/temp
intScrTime = 10  # set time for taking screen in seconds (120)`


Here is my current settings , just let me know do I have to set strScrDir , strLogFile and blnStoreLocal setting to False to get email working. What if there is no internet available then keys will be logged???
Is it correct setting for userp.

username = os.environ["USERNAME"]
strLogFile = "C:/Users/+username+/AppData/Local/Microsoft/Inteldat.txt"


Regards

**Comment by xp4xbox** [comment]
You have to set `blnStoreLocal` to false to use email. Also the way you set it up now, you will be receiving emails every 10 characters for `intCharPerSend`. If there is no internet then then the program will exit which is why I added the ability for it to be run at startup. For username it should be `"C:/Users/" 
+username+"/AppData/Local/Microsoft/Inteldat.txt"`
