### ISSUE TITLE
Protonmail 

### ISSUE THREAD

**Issue by joker8989** [xp4xbox/Puffader#33]
Hey i guess protonmail is the best email for using for keylogging : the data is encrypted and no one reads my mails..  
In gmail account they can add me to black list or block my account if they read it..
I have not test it yet but does the script Puffader send the logs to protonmail? For me its more safe then using gmail yahoo or other emails...

Is this will work?
https://protonmail.com

**Comment by xp4xbox** [comment]
Currently it only works with gmail, but the program uses SSH when sending the logs, so it is very secure. The way the program works, you enter your email and password, so what the program does is **send an email to yourself** using your email so that it is not possible to black list it.
