### ISSUE TITLE
convert to exe issue

### ISSUE THREAD

**Issue by joker8989** [xp4xbox/Puffader#34]
I tried to convert the puffader.py file to exe file to run in any windows machine the problem is cx_freeze_setup i run the command : python "cx_freeze_Setup.py" build and it created a exe file :)
but when i run the exe file from the file location(i put him for example in desktop)
i get an error (in a small windows) : 
cx_freeze Fatal Error

"cannot get zipimporter instance"
maybe u can help me?

i tried to convert it with pyinstaller and py2exe but the logs that i received in email are : 
䭥祬潧来爠却慲瑥搠䅴㨠〴⼰㈯㈰ㄸ‱㈺㔷㨴㐍਍਍਄؁ጆഊഊଁጆഊĆഊଓଌ؍ਁጆጁ؁ግਆē؁ጎ؍਋กግ਋؎ግ਋Ď؋ഊēฆഊଁጎ؍਋กጆഊ଎ē؎ēഊ؎ഊ଎؋ē؋ഊēญ਋؎ഊଁጎഊഊⴭⴍ੔桩猠敭慩氠桡猠扥敮⁣桥捫敤⁦潲⁶楲畳敳⁢礠䅖䜮ഊ桴瑰㨯⽷睷⹡癧⹣潭ഊഊ

lol

cx_freeze is the best way to do it right but i dont remember how i did it it was a long time ago....
the logs from cx_freeze were great(numbers,letters,symbols) everything...

any ideas? the  error from cx_freeze_setup???

**Comment by xp4xbox** [comment]
I removed cx_freeze since py2exe is the best option. Did you try the program without converting to .exe? It should not have outputted that.

**Comment by joker8989** [comment]
yea i tried the program without converting it works well...
py2exe is not so good try numbers and symbols there r not showing in the email (numbers at right side of the keyboard not the numbers where are : !@#!$!%%!)
it show me just letter(py2exe)

**Comment by joker8989** [comment]
what do you mean by "i removed cx_freeze ...." add cx_freeze again and see the difference...
you gotta help me with this error pls:...
cx_freeze Fatal Error

"cannot get zipimporter instance"

**Comment by tehseensagar** [comment]
py2exe work great with out any issue on windows just make sure you have installed all required dependencies for Puffader.

pip install pyautogui
pip install py2exe

download pywin32 and pyhook bindary for python 2.7


for binary file using py2exe
----------------------------
python setup.py

**Comment by joker8989** [comment]
I noticed after i posted my last post the i have not set something right and i succeeded thankx anyway..

**Comment by xp4xbox** [comment]
I removed support for cx_freeze since I do not like how it cannot compile program to standalone executable. Also instead of copying just modules that are needed over for the program, it copies every single one, even ones that are not in use. 

I also do not have much experience with it, so I cannot really help anyone with it.

thanks @tehseensagar
