### ISSUE TITLE
Webcam

### ISSUE THREAD

**Issue by joker8989** [xp4xbox/Puffader#36]
Hey i started to learn python so for now i can't do it along...
It will be nice if the script taking webcam stream on the victim machine like screebshot and send it to email/ftp server...

What it mean in stepa for example :
1. Check if the camera connected every 5 minutes
2. Streaming webcam for 10 min(you can choose the number of minutes like taking screenshots)
3.save the file in the victim machine in some location (that he won't see it of course)
4.send it to email/ftp
5.delete the file
Loop forever...

What do u think?

**Comment by xp4xbox** [comment]
I have already included the ability to take webcam snapshots in my python backdoor. In order to keep this program simplistic I would not include that feature.

**Comment by xp4xbox** [comment]
I will close this for now.
