### ISSUE TITLE
100 FUD%

### ISSUE THREAD

**Issue by joker8989** [xp4xbox/Puffader#39]
hey so i have found a "crypter" (NXCRYPT) in github that's make py file FUD i tried it on MSFVENOM-metasploit and it's worked 0/57 (without convert it to exe) i tried the same thing in Puffader and tried to change it to exe now when i converted it with py2exe i got an error: 
 

TypeError: compile() expected string without null bytes

maybe this is the way to make this script FUD in exe....

https://github.com/Hadi999/NXcrypt

**Comment by xp4xbox** [comment]
I tried it out, the program ran fine without compiling it. I am not sure why py2exe wont compile it. I am guessing since the program basically encrypts the program with gibberish text that it cant read.

**Comment by tehseensagar** [comment]
@joker8989  , well do not use that NXCrypt is does not work for now , Ive gone through the source file after  crypt. NX just added some junk paragraph in file and that does not understand by py2exe.  I'm also working on it to make it FUD once I succeeded I will share it. For now just hold on and keep try  other methods and share your views.

Regards

**Comment by joker8989** [comment]
I am just now trying to convert it to exe with the NXcrypt maybe i i will succeed , but with this junk code can be make python file FUD...?? am i wrong? its like a crypter in RAT..??

anyway @tehseensagar do u have a skype/email?

**Comment by tehseensagar** [comment]
@joker8989 contact me scorpoin@outlook.com
