### ISSUE TITLE
Little imporvment request

### ISSUE THREAD

**Issue by tehseensagar** [xp4xbox/Puffader#40]
First once exe run it should allow to delete from the path it run

For example if it is run form D:\puf\puf.exe  after execution it may be able to delete it or it should be melt by itself.

Second thing if any error occurred if should make a log in temp folder rather then on current path from where it is executed. For example D:\puf\

Thrid thing if Internet is off it does not killed but if any file created I.E screeshot it does not send back those files, there suppose to be a check if there is any file left after Internet connectivity resume it should send them back and then delete.

Regards

**Comment by xp4xbox** [comment]
1. I like this, I will add it soon.
2. I suggested adding the line 'sys.stderr = None' in the program to prevent any errors from showing since it is not possible to change location of file generated by py2exe (at least that I know of).
3. The way it is now, screenshots are of less priority so they will not be sent. I might consider fixing this.

**Comment by tehseensagar** [comment]
@xp4xbox  thank you so much for adding melt functionality. I've little confusion , correct me if I'm wrong. Application have intTimePerSend = 60 and intCharPerSend = 500 , in this particular setting logs will be send in every 1min right but keylog will be sent once it reaches to 500 keystroke right? once it reaches to 500 log created but internet disconnected and pc is shutdown? will it send log file next day once internet is available ? As I stated earlier there should be a check which look for any left over files and send those left over files once internet is connected.

Regards

**Comment by xp4xbox** [comment]
@tehseensagar If you set `blnUseTime` to be True, then it will override intCharPerSend. If the PC is shutdown the program is killed by the os, so any logs will be lost. Il try to get to that eventually for the feature.

**Comment by xp4xbox** [comment]
Also according to py2exe you can set the path for the log by doing sys.stderr = PATH.

**Comment by tehseensagar** [comment]
@xp4xbox  thank for your prompt response. Well setting local path will not send logs to any where I guess? It will keep them on system.

Regards

**Comment by xp4xbox** [comment]
It will keep them on the system.

**Comment by tehseensagar** [comment]
My concern is that a feature must be define which check any file letf over in system it must sent it back to server , if your setting is set to email.

Regards

**Comment by xp4xbox** [comment]
Im working on it.

**Comment by tehseensagar** [comment]
@xp4xbox  thanks dear , I will be waiting for it :).

**Comment by xp4xbox** [comment]
Closed 16dd47b
