### ISSUE TITLE
an other issue found

### ISSUE THREAD

**Issue by tehseensagar** [xp4xbox/Puffader#43]
I have build an exe on my laptop and port that exe to my desktop and ran it there. It ran with out any issue on my desktop pc , but it does not send any data on email nor creating any logs or screen shot in TMP directory as it is stand alone single binary file . Could you please have a look into this issue.

Regards

**Comment by tehseensagar** [comment]
@xp4xbox  brother any update on bug fix.

**Comment by xp4xbox** [comment]
I have no information on this issue. The program is currently running fine for me. Check to see if the program is running in task manager.

**Comment by xp4xbox** [comment]
Also, what OS are you running.

**Comment by tehseensagar** [comment]
I've found out some thing that will help this , I think issue is detection. Windows 10 even built AV security essential detecting it .

@xp4xbox  I would suggest to make some changes to avoid those detection.

Regards
