### ISSUE TITLE
Convert to exe not working

### ISSUE THREAD

**Issue by Destronuck** [xp4xbox/Puffader#47]
**OS:** [e.g. Windows 10]
**Commit/Build:** [e.g. b227928]

I have the code in python and set up as a .py file. But when I run it the dist folder pops up but there's nothing in it.

**Comment by xp4xbox** [comment]
First update to the latest commit, then if you still have problems post what it says in cmd.

**Comment by tehseensagar** [comment]
py2exe work great with out any issue on windows just make sure you have installed all required dependencies for Puffader.

pip install pyautogui
pip install py2exe

download pywin32 and pyhook bindary for python 2.7


for binary file using py2exe
----------------------------
python setup.py

**Comment by Destronuck** [comment]
Okay I've gotten it to work by downloading the master zip file (that I didn't know existed,) but there's an .exe called w9xpopen. Do I need this file or am I fine with just the puffader exe?

**Comment by xp4xbox** [comment]
You don't need it. For some reason py2exe bundles it on some systems.
