### ISSUE TITLE
Logging keyboard error.

### ISSUE THREAD

**Issue by ArlenRicard** [xp4xbox/Puffader#49]
I compiled the file, and I'm running the test on local computer, and configured to save the logs to a file. Recompiling a script multiple times after the problem, but the same error persisted in all tests, and no log file was generated.
The following tests are performed on virtual machines on the Windows 10 and Windows 7 operating systems. The following error is displayed by the Puffader log:

`Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "threading.pyc", line 754, in run
TypeError: StoreMessagesLocal() takes exactly 1 argument (138 given)

Exception in thread Thread-7:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "threading.pyc", line 754, in run
TypeError: StoreMessagesLocal() takes exactly 1 argument (185 given)

Exception in thread Thread-11:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "threading.pyc", line 754, in run
TypeError: StoreMessagesLocal() takes exactly 1 argument (349 given)`

**Comment by xp4xbox** [comment]
I have seen this before, for some reason it is passing in all of the characters as arguments.

**Comment by xp4xbox** [comment]
Try the latest commit.

**Comment by ArlenRicard** [comment]
Both of the virtual machines I used for the test are clean. I have installed only the pr requirements necessary to compile the project. I even installed everything software to do a quick search on the machine for this executable spbkhost.exe, but it does not exist.

**Comment by ArlenRicard** [comment]
@xp4xbox thanks for the speed in solving the problem!
The last commit, solved my problem, thank you!
