### ISSUE TITLE
Problem when using accent with puffader running.

### ISSUE THREAD

**Issue by ArlenRicard** [xp4xbox/Puffader#50]
Problem when using accent with puffader running.

When I initialize the puffader, the graphical accent no longer works correctly in any text editor, microsoft-word, notepad, etc ...
When I try to use the "**ã**" or "**á**" accent, any accent on the letters does not work. It is displayed only in the "**~~**" or "**´´**" or "**^^**" format.
This problem occurs both in the puffader and in the keylogger module of the python-backdoor project.

**Comment by ArlenRicard** [comment]
In the log file, the word is stored correctly, however in the text editor it does not.
In countries that use accentuation in writing, the puffader would not do well, since the system administrator would realize this problem that the user would report, and would certainly do a reinstallation of the operating system in order to solve this problem, eliminating the puffader.

**Comment by xp4xbox** [comment]
This is probably because of the PyHook module that I use and there is really nothing I can do about it.
