### ISSUE TITLE
Don't work properly on non-english SO (windows)

### ISSUE THREAD

**Issue by not3nough** [xp4xbox/Puffader#52]
**OS:** [e.g. Windows 10]
**Commit/Build:** [e.g. b227928]

Hi, 

It seems that I can't properly use '´' accent´or '^' when pyHook is running. It seems that I can't properly use '^' accents when pyHook is running. My keyboard is non-english (spanish). Can't accentuate words too.

**Comment by xp4xbox** [comment]
Unfortunately there is nothing I can do about this since it is related to the pyhook module.
