### ISSUE TITLE
Any way to log remote errors?

### ISSUE THREAD

**Issue by Nisthar** [xp4xbox/Puffader#56]
Currently, I get it working for some pc's. But it doesn't work on some machines.

Is there any way to log remote errors ?

**Comment by xp4xbox** [comment]
ATM it is not.

**Comment by Nisthar** [comment]
@xp4xbox The current problem is its not efficient. It doesn't work on some computers. It sometimes doesn't work on my computer. I checked my regedit. It has the key for running in the startup. But the app is not running.

So, it needs a way to ensure the connection doesn't lose or log the last time a computer has connected.

**Comment by xp4xbox** [comment]
It is a bug with the program then and should be fixed. I am not sure why it would not work on some systems. Anyway it is possible to log errors, but only locally.

**Comment by vladimirpe00** [comment]
any error logs? so you can trace the issue?

**Comment by xp4xbox** [comment]
This is the problem with python, it's very unreliable.
