### ISSUE TITLE
cannot import name GetKeyState

### ISSUE THREAD

**Issue by user568989** [xp4xbox/Puffader#57]
When i tried to run the script after i installed all the modules i get this error : 

Traceback (most recent call last):
  File "C:\Users\blabla\Desktop\Puffader-master\Puffader.py", line 15, in <module>
  

  from pyHook import GetKeyState, HookConstants
ImportError: cannot import name GetKeyState

any ideas?

**Comment by xp4xbox** [comment]
Are you using python 2.7?

**Comment by user568989** [comment]
Yes 2.7.13

**Comment by user568989** [comment]
Why i get this error?

**Comment by user568989** [comment]
I see you added codes in the script i see now that you added modules...

Anyway is there a solution to my error?

**Comment by user568989** [comment]
Solved

**Comment by xp4xbox** [comment]
How did you solve it

**Comment by user568989** [comment]
sorry for the delay could not check my email anyway i dont know how i
solved it i just downloaded puffader again of course i changed something i
dont know exactly how but i solved it ... need little bit to play with
these kind of script cause it does not work 100% as you want


i wanted to ask u if u r developing this script anyway ? or it will stay
like this for ever ..
i thought you can add some new features like "password recovery" like
Lazagne
https://github.com/AlessandroZ/LaZagne

or maybe "webcam recording" you can send to email like you send screenshot
(maybe save the video to a file in "TEMP" for example and then send it to
email...

**Comment by xp4xbox** [comment]
I am still developing this when I am in the mood to. If you could find out what exactly you did to make it work that would be appreciated.
