### ISSUE TITLE
Detectable 

### ISSUE THREAD

**Issue by kingexplosionMurder** [xp4xbox/Puffader#59]
The keylogger hasn’t been working recently and it has become detectable, is there anything you can do about this.

**Comment by xp4xbox** [comment]
Is the only problem that it has been detectable?

**Comment by kingexplosionMurder** [comment]
Yes that’s all I’ve noticed for now

**Comment by kingexplosionMurder** [comment]
It was detected by Avira

**Comment by kingexplosionMurder** [comment]
Is there anything you can do about it being detectable

**Comment by xp4xbox** [comment]
I am not sure.

Maybe someone could help.

**Comment by user568989** [comment]
A script like NXcreypt should do the trick its just add some junk code and it 100 FUD.. i dont know how long it will keep your file FUD but of course you need to run some tests..

**Comment by xp4xbox** [comment]
it doesnt work with py2exe
