### ISSUE TITLE
Adding photo

### ISSUE THREAD

**Issue by Haskileto** [xp4xbox/Puffader#60]
**Hi, i'm kinda new to this sort of stuff but i would like you to help me, so i was seeing your code for school research, but i would like to know if i could add some photo?
I mean i would like to know if in this code i could get a photo to be opened and at the same time run your code. Is that possible?
Thanks in advance.**

**Comment by xp4xbox** [comment]
Yeah that's very basic stuff, I recommend learning python before that.
