### ISSUE TITLE
Meterpreter connection..

### ISSUE THREAD

**Issue by user568989** [xp4xbox/Puffader#61]
Is there a way to get meterpreter everytime the system reboots i mean if the victim run the puffader(puffader includes meterpreter)
The attacker will get keylogger keystrokes and meterpreter session but if the victim reboots the puffader will keep running and meterpreter won't

Is there a way to keep meterpreter running after the victim reboots cause puffader run correctly..

Also multiple clients..

**Comment by xp4xbox** [comment]
It is not possible to do that since meterpreter is part of the Puffader process. If you want something like that, I recommend checking out my other project. https://github.com/xp4xbox/Python-Backdoor
