### ISSUE TITLE
No content in the email

### ISSUE THREAD

**Issue by michalmarkus** [xp4xbox/Puffader#62]
I have a problem when I get emails - there is no content for this something like on the screen http://www.mediafire.com/view/467y4knauusq6ya/test.jpg/file

What's the problem ?

**OS:** [e.g. Windows 10]
**Commit/Build:** [e.g. b227928]

**Comment by xp4xbox** [comment]
I have never seen that before. I just tested it out and I dont have that problem. Try reinstalling all modules.

**Comment by michalmarkus** [comment]
I made a new virtual machine with Win7 32Bit on which I installed python 2.7

The problem is the same - the email subject is correct and gives the IP and the host name,


I found a problem:
```
Traceback (most recent call last):
  File "pyHook\HookManager.pyc", line 351, in KeyboardSwitch
  File "Puffader.py", line 250, in OnKeyboardEvent
```

installed modules
```
c:\Python27>pip list
Package    Version
---------- ----------
certifi    2018.10.15
chardet    3.0.4
idna       2.7
Pillow     5.3.0
pip        18.1
py2exe     0.6.9
pyHook     1.5.1
PyScreeze  0.1.18
pywin32    224
requests   2.20.1
setuptools 18.2
urllib3    1.24.1

c:\Python27>pip -V
pip 18.1 from c:\python27\lib\site-packages\pip (python 2.7)

c:\Python27>python -V
Python 2.7.11
```

**Comment by xp4xbox** [comment]
Weird.

**Comment by michalmarkus** [comment]
Ok the problem disappeared when I made compilations on Windows 10
