### ISSUE TITLE
Avast alarm

### ISSUE THREAD

**Issue by michalmarkus** [xp4xbox/Puffader#63]
Avast raised the alarm about malware. Can you cheat him somehow?

**OS:** [e.g. Windows 10]
**Commit/Build:** [e.g. b227928]

**Comment by xp4xbox** [comment]
I am not sure, it used to be undetectable. I have heard of this https://github.com/Hadi999/NXcrypt but it doesnt work when the file is compiled to .exe.

**Comment by vladimirpe00** [comment]
you python crypter that can handle python code before it converted to exe besides try to modify your scri[t changing functions name in order to change the code signature it seems a lot of people are using it which flagged the code

**Comment by xp4xbox** [comment]
That would be up to the user

**Comment by ghost** [comment]
Bitdefender alarms too.
But after I turned the addtostartup to false, it was fixed. 

Antivirus is assuming it to be worm(as it is copying itself).

**Comment by xp4xbox** [comment]
Yeah, there is nothing I can do about it.

**Comment by ghost** [comment]
Can't you make a shortcut in startup folder instead of moving the exe file?
I think this can help

**Comment by xp4xbox** [comment]
That would make it even more detectable
