### ISSUE TITLE
32x system

### ISSUE THREAD

**Issue by ghost** [xp4xbox/Puffader#65]
**OS:** [e.g. Windows 10]
**Commit/Build:** [e.g. b227928]

Its not compatible with x86 systems ?

**Comment by xp4xbox** [comment]
It is, I wrote the entire program on a 32 bit laptop.

**Comment by ghost** [comment]
Operating System : Windows 7 32bit

This is Error Message:
` The version of this file is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need an x86 (32bit) or x64 (64bit) version of the program, and then contact the software publisher `


Screenshot Link:
https://cdn1.imggmi.com/uploads/2019/1/29/8a783b738ed23a58bccb47c71722f602-full.png


Thanks
