### ISSUE TITLE
isn't urllib2 depricated?

### ISSUE THREAD

**Issue by veryyynice** [xp4xbox/Puffader#67]
**OS:** [e.g. Windows 10]
**Commit/Build:** [e.g. b227928]

when I try to run puffader with python 2.7 it says that there no module named urllib2

**Comment by NicolasHawrysh** [comment]
Works last time I used it. Not sure

**Comment by xp4xbox** [comment]
Worked last time I tried it. 

EDIT: Works when I tried it today.

**Comment by veryyynice** [comment]
I went and copied the original code from this repository and it worked..
