### ISSUE TITLE
How can I send .doc file as attachment?

### ISSUE THREAD

**Issue by ghost** [xp4xbox/Puffader#68]
**OS:** [e.g. Windows 10]
**Commit/Build:** [e.g. b227928]

I am trying to mail .doc files but as i m new to python, can't figure the way out.
Kindly guide me.........

**Comment by xp4xbox** [comment]
Like kinda like this.

```
objMsg = MIMEMultipart()
objMsg["Subject"] = "SUBJECT"

filename = "text.doc"
f = file(filename)
attachment = MIMEText(f.read())
attachment.add_header('Content-Disposition', 'attachment', filename=filename)           
objMsg.attach(attachment)

SmtpServer = smtplib.SMTP_SSL("smtp.gmail.com", 465); SmtpServer.ehlo()
SmtpServer.login(strEmailAc, strEmailPass)
SmtpServer.sendmail(strEmailAc, strEmailAc, objMsg.as_string())
SmtpServer.close()
```

**Comment by ghost** [comment]
Corrupted doc attachment. Can't open it 
And Thanks for prompt reply.

**Comment by xp4xbox** [comment]
You probably have to add, `f.close()` after the `attachment = MIMEText(f.read())`.

Also make sure you are using correct path.

**Comment by ghost** [comment]
Again same error
i think that the file cannot be opened in text format.
any other way to send it
Thanks in advance

**Comment by xp4xbox** [comment]
Maybe try opening file as byte. So `f = file(filename, "rb")`

**Comment by ghost** [comment]
It's almost resolve but the attachment is still corrupted.
Instead the body of the email contain the matter present in .doc file

But it comes with lot of residue.
Thanks in advance

**Comment by xp4xbox** [comment]
https://stackoverflow.com/questions/11921188/how-to-send-email-with-pdf-attachment-in-python

Here is how. Should work with doc.

**Comment by ghost** [comment]
Thanks,
Solved
