### ISSUE TITLE
error with compiling puffader.py 

### ISSUE THREAD

**Issue by veryyynice** [xp4xbox/Puffader#69]
**OS:** [e.g. Windows 10]
**Commit/Build:** [e.g. b227928]

when I compile Puffader.py with 'py -2.7 -B ./setup.py' it stops at *** byte compile python files *** ...
 ```
byte-compiling C:\Python27\lib\encodings\cp1252.py to encodings\cp1252.pyc
berror: [Errno 2] No such file or directory
```

**Comment by xp4xbox** [comment]
Never got that error before, try re-installing python.
