### ISSUE TITLE
Ports available to send email.

### ISSUE THREAD

**Issue by ghost** [xp4xbox/Puffader#71]
**OS:** [e.g. Windows 10]
**Commit/Build:** [e.g. b227928]

I am trying to run puffader on 4 different machines on the same network but using port 465 on all of them isn't helping.

Problem: Only one of them is sending emails.

I searched for the ports that i can use but stuck on only two(465 and 587)

Can you provide solution to this Problem.
Please respond ASAP.....It's little urgent.

**Comment by xp4xbox** [comment]
The port should not change, that is probably not that problem.

**Comment by ghost** [comment]
Thanks for responding..
All of them use different emails.
Can this be the problem.

Rest all the code is same....
