### ISSUE TITLE
Compiling to exe errors.

### ISSUE THREAD

**Issue by OH3Xs** [xp4xbox/Puffader#73]
OS: Windows 10

Hi, I'm currently getting this issue. I tried in any other PC/Laptop but it's still the same errors.

Sorry about this and this is my First time in Python. I hope you understand my situation.

Error Logs:
`C:\Users\Vane\Desktop\Puffader-master>python setup.py
running py2exe
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    zipfile = None,
  File "

C:\Users\Vane\AppData\Local\Programs\Python\Python37-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "

C:\Users\Vane\AppData\Local\Programs\Python\Python37-32\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "

C:\Users\Vane\AppData\Local\Programs\Python\Python37-32\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "

C:\Users\Vane\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py2exe\distutils_buildexe.py", line 188, in run
    self._run()
  File "

C:\Users\Vane\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py2exe\distutils_buildexe.py", line 267, in _run
    builder.analyze()
  File "

C:\Users\Vane\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py2exe\runtime.py", line 160, in analyze
    self.mf.import_hook(modname)
  File "

C:\Users\Vane\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py2exe\mf3.py", line 120, in import_hook
    module = self._gcd_import(name)
  File "

C:\Users\Vane\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py2exe\mf3.py", line 274, in _gcd_import
    return self._find_and_load(name)
  File "

C:\Users\Vane\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py2exe\mf3.py", line 357, in _find_and_load
    self._scan_code(module.__code__, module)
  File "

C:\Users\Vane\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py2exe\mf3.py", line 401, in _scan_code
    self._scan_code(c, mod)
  File "

C:\Users\Vane\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py2exe\mf3.py", line 388, in _scan_code
    for what, args in self._scan_opcodes(code):
  File "

C:\Users\Vane\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py2exe\mf3.py", line 417, in _scan_opcodes
    yield "store", (names[oparg],)
IndexError: tuple index out of range`

**Comment by xp4xbox** [comment]
Your problem is your using python 3.7, this program only works with python 2.7

**Comment by OH3Xs** [comment]
> 
> 
> Your problem is your using python 3.7, this program only works with python 2.7

Thanks, it works now!

**Comment by OH3Xs** [comment]
Btw why there are two exe files? and which one should be executed first? the Puffader one or w9xpopen?

**Comment by xp4xbox** [comment]
w9xpopen can be deleted.
