### ISSUE TITLE
bundle-files 1 not yet supported on win64

### ISSUE THREAD

**Issue by gagandeep1994** [xp4xbox/Puffader#74]
whenever i run python setup.py it throws a error saying bundle-files 1 not yet supported on win64
can you help?

**Comment by xp4xbox** [comment]
When does this error show. After you configure all setings?

**Comment by gagandeep1994** [comment]
it doesn't start, i have installed everything. do i have to paste the setup.py and puffader.py in python27 folder C: ? i have tried that also and i have also tried running it from the puffader-master folder. sorry i'm new to python but yes i did all the installation like pyhook, py2exe, everything but when i run the setup.py file it shows me a error. maybe because i'm on win7 64 bit version?

**Comment by gagandeep1994** [comment]
Sir i have configure all the settings inside the puffader.py file (email id,pass, on which folder to save the ss and log file too, also "/" instead of "\"), and i followed all your steps.. i have installed everything, also allowed less secure apps. but it doesn't start. only error i'm getting is this and i also git clone as per your steps. sorry i'm new to python. this is the dir and when i run python setup.py it shows this.
https://imgur.com/a/5Fbu4Rs

**Comment by gagandeep1994** [comment]
Sir i have configure all the settings inside the puffader.py file (email id,pass, on which folder to save the ss and log file too. i followed all your steps..maybe because i'm on win7 64bit version?? i have installed everything, also allowed less secure apps. but it doesn't start. only error i'm getting is this and i also git clone as per your steps. sorry i'm new to python. this is the dir and when i run python setup.py it shows this.
https://imgur.com/a/5Fbu4Rs

**Comment by xp4xbox** [comment]
Remove the line in setup.py that says bundlefiles:1

And the comma on the end of the line above it.

**Comment by gagandeep1994** [comment]
i removed the bundlesfiles :1 and also the comma and now it started but now it showing this
https://imgur.com/a/bNdpLe6

**Comment by xp4xbox** [comment]
ok, i have a better idea, uninstall everything than reinstall everything using the 32bit downloads.

**Comment by gagandeep1994** [comment]
okay sir i will reinstall everything and let you know. thank you

**Comment by gagandeep1994** [comment]
i installed 32 bit version all of them.. and now it is not showing any sort of error. i hope it will work now.. after running setup.py there is dist folder that has been created. i can see .exe file. so this is it? thank you so much sir! which one exe to run ??
https://imgur.com/a/8NcJh5V

Edit : oh yes after double clicking puffader.exe i can see that running in background in task manager but can't see any ss in temp folder and also text file which i have created is 0 kb. i guess i have to wait to see what is happening. (i have also inserted email id n password). thank you sir

**Comment by xp4xbox** [comment]
yeah the other file can be deleted.
