### ISSUE TITLE
Weird Logs Encoding that have been sent by EMail

### ISSUE THREAD

**Issue by ipenywis** [xp4xbox/Puffader#75]
**OS:** Windows 10 Pro
**Commit/Build:** 17134.950

The loggin mechanisme is working but the problem is in the Encoding format of the sent logs by mail I get something like this
![image](https://user-images.githubusercontent.com/13965825/65782040-bad41e00-e144-11e9-83ab-6f6ce58e41f6.png)

Im testing it in my **English Windows 10 Pro** machine where I am typing in English.

Any suggestions of what is exactly the problem and how to fix it?

**Comment by xp4xbox** [comment]
im not sure i never had that problem before.

**Comment by xp4xbox** [comment]
Honestly, Python2.7 is a mess i recommend you check out https://github.com/xp4xbox/Python-Backdoor this project isnt really supported anymore.

**Comment by ipenywis** [comment]
- I fixed the issue it was a **python 2.7**  with pyhooks issue which it returns non-ASCII  for  `event.ascii` so I had to modify the code to use `event.KeyID` which returns the **ASCII**  Representation of the event key.

Thanks for your help anyway.

I will check Python Backdoor it seems interesting.
